FROM ubuntu:20.04 as builder

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    git \
    libboost-all-dev \
    libsfml-dev

WORKDIR /usr/src/
COPY . .

RUN mkdir build && cd build && cmake .. && make

FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    libboost-system-dev \
    libboost-asio-dev \
    libboost-iostreams-dev \
    libsfml-dev

WORKDIR /usr/src/

COPY --from=builder /usr/src/build/r-type_server .

EXPOSE 8080

CMD ["./r-type_server", "8080"]
